
exec >/dev/kmsg 2>&1

LF=$'\n'
config_dir="$(dirname "$(dirname "$0")")/system"
normal_dir="$1"
early_dir="$2"
late_dir="$3"

rm -f /run/$UNIT_NAME/*.generated

gen_addr(){
    $BIN gen "$@"
    return $?
}

# cannot create temp file for here-document: Read-only file system
(cd "$config_dir"; egrep -r "^Generate${UNIT_TITLE}=" .) | cut -d: -f1 | sed 's:^\./::' | uniq | while read file; do
  prog=(
    -e "1 i # Generated by $0"
    -e "/^\[Unit\]/ { a SourcePath=$config_dir/$file$LF}"
    -e "/^Generate${UNIT_TITLE}=.*/ d"
    -e "/^Generated${UNIT_TITLE}WantedBy=.*/ d"
    -e "/^Generated${UNIT_TITLE}RequiredBy=.*/ d"
  )
  touch "$early_dir/$file"
  for addr in $(sed -n "s/^Generate${UNIT_TITLE}=//p" "$config_dir/$file" | xargs); do
    gen_addr "$addr" "$early_dir/$file"
    addr4="$(sed -n 's/^HOSTADDR4=//p' /run/$UNIT_NAME/$addr.env)"
    addr6="$(sed -n 's/^HOSTADDR6=//p' /run/$UNIT_NAME/$addr.env)"
    prog+=(-e "s/\\\${${UNIT_NAME}4@${addr}}/${addr4}/g")
    prog+=(-e "s/\\\${${UNIT_NAME}6@${addr}}/${addr6}/g")
  done
  mkdir -p "$early_dir/$(dirname "$file")"
  sed "${prog[@]}" "$config_dir/$file" >"$early_dir/$file"

  # handle installation (if original unit is installed)
  # find /etc/systemd/system/ -maxdepth 2 -mindepth 2 -type l -name $file
  (cd "$config_dir"; ls */$file 2>/dev/null) | while read path; do
    dep="${path%/*}"
    mkdir -p "$early_dir/$dep"
    ln -s "../$file" "$early_dir/$dep/$file"
  done

  # handle specific GeneratedAddrWantedBy= directives
  for dep in $(sed -n "s/^Generated${UNIT_TITLE}WantedBy=//p" "$config_dir/$file" | xargs); do
    mkdir -p "$early_dir/$dep.wants"
    ln -s "../$file" "$early_dir/$dep.wants/$file"
  done

  # handle specific GeneratedAddrRequiredBy= directives
  for dep in $(sed -n "s/^Generated${UNIT_TITLE}RequiredBy=//p" "$config_dir/$file" | xargs); do
    mkdir -p "$early_dir/$dep.requires"
    ln -s "../$file" "$early_dir/$dep.requires/$file"
  done
done

